# Generated by Django 3.2 on 2022-08-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dweller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('social_status', models.CharField(choices=[('Knight', 'Рыцарь'), ('Landlord', 'Землевладелец'), ('Merchant', 'Купец')], max_length=255)),
                ('salary_per_month', models.IntegerField()),
            ],
            options={
                'db_table': 'estates_dwellers',
            },
        ),
        migrations.CreateModel(
            name='Monarch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reign_started', models.DateField()),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estates_monarchs',
            },
        ),
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('king', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.monarch')),
            ],
            options={
                'db_table': 'estates_seniors',
            },
        ),
        migrations.CreateModel(
            name='Peasant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.dweller')),
            ],
            options={
                'db_table': 'estates_peasants',
            },
        ),
        migrations.AddField(
            model_name='dweller',
            name='obeys_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.senior'),
        ),
    ]
